config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'

  get 'home', to: 'welcome#home'

  resources :users, only: %i[index]
  post 'login', to: 'users#login'
  delete 'logout', to: 'users#logout'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  after_create :encrypt_password

  validates :username, :password, :status, :login_attempts, presence: true
  validates :username, uniqueness: true
  validates :username, length: { minimum: 6 }
  validates :password, length: { minimum: 6 }

  enum status: %i[active blocked]

  def encrypt_password
    self.password = Digest::MD5.hexdigest(password)
    save
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    return :ok if session[:current_user].present?

    @username = params[:username]
    @password = params[:password]

    if valid_params?
      redirect_to home_path
    else
      redirect_to root_path
    end
  end

  def valid_params?
    return false unless @username.present? && @password.present?

    valid_user_credentials?
  end

  def valid_user_credentials?
    @current_user = User.find_by(username: @username)

    if @current_user
      if Digest::MD5.hexdigest(@password) == @current_user.password
        return false unless @current_user.active?

        reset_login_attempts
        create_user_session
        @current_user
      else
        login_failure
        false
      end
    else
      new_user
    end
  end

  def reset_login_attempts
    @current_user.update(login_attempts: 0) if @current_user.login_attempts.positive?
  end

  def create_user_session
    session[:current_user] = @current_user
  end

  def login_failure
    if @current_user.login_attempts < 3
      @current_user.login_attempts += 1
      @current_user.save
    end
    @current_user.blocked! if @current_user.login_attempts >= 3
  end

  def new_user
    @current_user = User.new(username: @username, password: @password)
    if @current_user.save
      create_user_session
      @current_user
    else
      false
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    redirect_to home_path if session[:current_user]
  end

  def login
    authenticate_user!
  end

  def logout
    session[:current_user] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def home
    @current_user = session[:current_user]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>LOGIN</h1>

Please attention!
<ul>
  <li>minimum length for username: 6.</li>
  <li>minimum length for password: 6.</li>
  <li>a new user will be created and logged in if no user could be found with correct username/password.</li>
  <li>user will be blocked after 3 consecutives logon failures!</li>
</ul>

<%= form_tag(login_path) do %>
  <div>Username: <%= text_field_tag :username %></div>
  <div>Password: <%= password_field_tag :password %></div>
  <div><%= submit_tag 'Login' %></div>
<% end %>

app/views/welcome/home.html.erb
<h1>HOME</h1>

<%= @current_user %>

<hr>

<%= link_to :logout, logout_path, method: :delete %>